version: "3.8"

services:
  php:
    image: php:mysqli
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
    environment:
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DB
  mysql:
    image: mysql:5.7
    ports:
      - 33065:3306
    volumes:
      - devphp-mysql-data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE

volumes:
  devphp-mysql-data:  